### ISSUE TITLE
Memory Error in Colab

### ISSUE THREAD

**Issue by Bammargiela** [rinongal/textual_inversion#127]
https://imgur.com/q7eTJE2

It says this when I hover over

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.16 GiB (GPU 0; 14.76 GiB total capacity; 10.28 GiB already allocated; 287.75 MiB free; 13.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I've tried doing less images, running with the default images, running with and without xformers. I even bought Colab Pro thinking that might be the issue. It seems to be working for plenty of people so I'm unsure why it would be different for me. I'm about a week into AI art and 2 days into SD with no coding knowledge so any help is greatly appreciated. Thanks

**Comment by rinongal** [comment]
Hey - whose Colab is this? Diffusers? We don't have an official Colab implementation.

Would need more details to help.

**Comment by Bammargiela** [comment]
Ah I understand. Yes it is the diffusers Colab.

**Comment by Bammargiela** [comment]
I am running it now and it seems to have made it pass the part where I was getting the error. Turns out I needed to change my GPU class to premium in Runtime > Change Runtime. That way I actually use the premium Colab I paid for lol.

**Comment by rinongal** [comment]
Great! I'm not entirely familiar with the diffusers code, but if you get stuck let me know and I'll try to have a look.
If this is resolved, please close the issue.

**Comment by Bammargiela** [comment]
Appreciate that!
